project: linux
project_url: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/
new_patch: 4e302336d5ca1767a06beee7596a72d3bdc8d983
new_patch_parent: f3fb462443a5e150599fa6692e660e25c974e7be
target_release: 8374bcb27120253f710216cd1cc1be25adfcdea3
sanitizer: 
error_message: 
tag: 853a6f4dfa3cf37d3aea
project_dir: /path/to/local/linux-stable
patch_dataset_dir: /path/to/KBack-artifact/paired_patches/853a6f4dfa3cf37d3aea
api_key: <REDACTED>
api_url: <REDACTED>
model: gpt-4o-mini
oracle_enabled: false
