project: linux
project_url: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/
new_patch: f024d3a8ded0d8d2129ae123d7a5305c29ca44ce
new_patch_parent: edd43f4d6f50ec3de55a0c9e9df6348d1da51965
target_release: a21cb31642ffc84ca4ce55028212a96f72f54d30
sanitizer: 
error_message: 
tag: 3e77fd302e99f5af9394
project_dir: /path/to/local/linux-stable
patch_dataset_dir: /path/to/KBack-artifact/paired_patches/3e77fd302e99f5af9394
api_key: <REDACTED>
api_url: <REDACTED>
model: gpt-4o-mini
oracle_enabled: false
