project: linux
project_url: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/
new_patch: befe6d946551d65cddbd32b9cb0170b0249fd5ed
new_patch_parent: f2a99ddfd0aaff5f5c53ea1f652b5160ba5ee9b7
target_release: 7b43f95c1fa9f91146f592271bb194b8b396fb0b
sanitizer: 
error_message: 
tag: 83aa762ef23b6f0d1991
project_dir: /path/to/local/linux-stable
patch_dataset_dir: /path/to/KBack-artifact/paired_patches/83aa762ef23b6f0d1991
api_key: <REDACTED>
api_url: <REDACTED>
model: gpt-4o-mini
oracle_enabled: false
