project: linux
project_url: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/
new_patch: cb7a95af78d29442b8294683eca4897544b8ef46
new_patch_parent: a689b938df39ab513026c53fb7011fd7cd594943
target_release: 0c7d45c2d30ed7312e66187978bf7cf7349cd3c7
sanitizer: 
error_message: 
tag: 7bb7cd3595533513a9e7
project_dir: /path/to/local/linux-stable
patch_dataset_dir: /path/to/KBack-artifact/paired_patches/7bb7cd3595533513a9e7
api_key: <REDACTED>
api_url: <REDACTED>
model: gpt-4o-mini
oracle_enabled: false
