project: linux
project_url: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/
new_patch: 08d1914293dae38350b8088980e59fbc699a72fe
new_patch_parent: 500257db81d067c1ad5a202501a085a8ffea10f1
target_release: cce8419b8168f6e7eb637103a47f916f3de8bc81
sanitizer: 
error_message: 
tag: d7ce59b06b3eb14fd218
project_dir: /path/to/local/linux-stable
patch_dataset_dir: /path/to/KBack-artifact/paired_patches/d7ce59b06b3eb14fd218
api_key: <REDACTED>
api_url: <REDACTED>
model: gpt-4o-mini
oracle_enabled: false
