project: linux
project_url: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/
new_patch: ad9d24c9429e2159d1e279dc3a83191ccb4daf1d
new_patch_parent: b87b04f5019e821c8c6c7761f258402e43500a1f
target_release: 0239c439cedcc13c57f6d6e47c36904cdf1da7ca
sanitizer: 
error_message: 
tag: 1917d778024161609247
project_dir: /path/to/local/linux-stable
patch_dataset_dir: /path/to/KBack-artifact/paired_patches/1917d778024161609247
api_key: <REDACTED>
api_url: <REDACTED>
model: gpt-4o-mini
oracle_enabled: false
