project: linux
project_url: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/
new_patch: 6ef09cdc5ba0f93826c09d810c141a8d103a80fc
new_patch_parent: 0941772342d59e48733131ac3a202fa1a4d832e9
target_release: 4871dd2f7193c00ced0317b76bdda4fbb7381785
sanitizer: 
error_message: 
tag: 253cd2d2491df77c93ac
project_dir: /path/to/local/linux-stable
patch_dataset_dir: /path/to/KBack-artifact/paired_patches/253cd2d2491df77c93ac
api_key: <REDACTED>
api_url: <REDACTED>
model: gpt-4o-mini
oracle_enabled: false
