project: linux
project_url: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/
new_patch: 9b91b6b019fda817eb52f728eb9c79b3579760bc
new_patch_parent: 9011c2791e63fc05721b545c41ad025d8073566e
target_release: 75004b47fba41ffba1c779350d9e457ace11cc6b
sanitizer: 
error_message: 
tag: 579885d1a9a833336209
project_dir: /path/to/local/linux-stable
patch_dataset_dir: /path/to/KBack-artifact/paired_patches/579885d1a9a833336209
api_key: <REDACTED>
api_url: <REDACTED>
model: gpt-4o-mini
oracle_enabled: false
