project: linux
project_url: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/
new_patch: 2f38cf730caedaeacdefb7ff35b0a3c1168117f9
new_patch_parent: 5fa87a081b2d633b944d5a93f5767623ef2a961d
target_release: 5472b587cf71f72fa4be675c30fab677e65c6f63
sanitizer: 
error_message: 
tag: 78d5b129a762182225aa
project_dir: /path/to/local/linux-stable
patch_dataset_dir: /path/to/KBack-artifact/paired_patches/78d5b129a762182225aa
api_key: <REDACTED>
api_url: <REDACTED>
model: gpt-4o-mini
oracle_enabled: false
