project: linux
project_url: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/
new_patch: c344f07aa1b4ba38ca8fabe407a2afe2f436323c
new_patch_parent: caf231ac25bdde69d257366e2f8d13b37af5458e
target_release: 17d7af0796cfd169c9309445f8b42fd1ad698688
sanitizer: 
error_message: 
tag: 142888ffec98ab194028
project_dir: /path/to/local/linux-stable
patch_dataset_dir: /path/to/KBack-artifact/paired_patches/142888ffec98ab194028
api_key: <REDACTED>
api_url: <REDACTED>
model: gpt-4o-mini
oracle_enabled: false
