project: linux
project_url: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/
new_patch: 4481f7f2b3df123ec77e828c849138f75cff2bf2
new_patch_parent: 0af2f6be1b4281385b618cb86ad946eded089ac8
target_release: c2a952fb41cc5575b5b9fa22b9642b3b5070c6a3
sanitizer: 
error_message: 
tag: 25b83a6f2c702075fcbc
project_dir: /path/to/local/linux-stable
patch_dataset_dir: /path/to/KBack-artifact/paired_patches/25b83a6f2c702075fcbc
api_key: <REDACTED>
api_url: <REDACTED>
model: gpt-4o-mini
oracle_enabled: false
