project: linux
project_url: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/
new_patch: 2afd4d267e6dbaec8d3ccd4f5396cb84bc67aa2e
new_patch_parent: 1f2bf7049f6ef6048b56b18d0033d3e77b28f973
target_release: 1605de8102b8a00321afa5d1fed50133bf7198b9
sanitizer: 
error_message: 
tag: 73d8fc29ec7cba8286fa
project_dir: /path/to/local/linux-stable
patch_dataset_dir: /path/to/KBack-artifact/paired_patches/73d8fc29ec7cba8286fa
api_key: <REDACTED>
api_url: <REDACTED>
model: gpt-4o-mini
oracle_enabled: false
