project: linux
project_url: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/
new_patch: e7a7ef9a0742dbd0818d5b15fba2c5313ace765b
new_patch_parent: ea63fb71993c56628f323b8268d36f4bbd836a7f
target_release: 3b839d4619042b02eecdfc986484ac6e6be6acbf
sanitizer: 
error_message: 
tag: 8dd98a9e98ee28dc484a
project_dir: /path/to/local/linux-stable
patch_dataset_dir: /path/to/KBack-artifact/paired_patches/8dd98a9e98ee28dc484a
api_key: <REDACTED>
api_url: <REDACTED>
model: gpt-4o-mini
oracle_enabled: false
