project: linux
project_url: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/
new_patch: 8a924db2d7b5eb69ba08b1a0af46e9f1359a9bdf
new_patch_parent: b85ea95d086471afb4ad062012a4d73cd328fa86
target_release: 21bffb862ca0ce02f4a0f742e7e616fb75071362
sanitizer: 
error_message: 
tag: a67fc5321ffb4b311c98
project_dir: /path/to/local/linux-stable
patch_dataset_dir: /path/to/KBack-artifact/paired_patches/a67fc5321ffb4b311c98
api_key: <REDACTED>
api_url: <REDACTED>
model: gpt-4o-mini
oracle_enabled: false
