project: linux
project_url: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/
new_patch: e24c1551059268b37f6f40639883eafb281b8b9c
new_patch_parent: d9df72c6acd683adf6dd23c061f3a414ec00b1f8
target_release: 5d679086873fe9a51354ceaddb8937ac589520d0
sanitizer: 
error_message: 
tag: 85992ace37d5b7b51635
project_dir: /path/to/local/linux-stable
patch_dataset_dir: /path/to/KBack-artifact/paired_patches/85992ace37d5b7b51635
api_key: <REDACTED>
api_url: <REDACTED>
model: gpt-4o-mini
oracle_enabled: false
