project: linux
project_url: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/
new_patch: eaaea4681984c79d2b2b160387b297477f0c1aab
new_patch_parent: 48e15418e41e4f32bb96dd8af1ae4a89ae13157b
target_release: 22d384052a6abe6637808672c79a3868f60e29b9
sanitizer: 
error_message: 
tag: a4e309017a5f3a24c7b3
project_dir: /path/to/local/linux-stable
patch_dataset_dir: /path/to/KBack-artifact/paired_patches/a4e309017a5f3a24c7b3
api_key: <REDACTED>
api_url: <REDACTED>
model: gpt-4o-mini
oracle_enabled: false
