project: linux
project_url: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/
new_patch: a0312af1f94d13800e63a7d0a66e563582e39aec
new_patch_parent: de925e2fbb44eed8a2a7ce166b485fed5eae01aa
target_release: 758ed157fdae5e6a9ff3eeebebed46652b09c97f
sanitizer: 
error_message: 
tag: 1e911ad71dd4ea72e04a
project_dir: /path/to/local/linux-stable
patch_dataset_dir: /path/to/KBack-artifact/paired_patches/1e911ad71dd4ea72e04a
api_key: <REDACTED>
api_url: <REDACTED>
model: gpt-4o-mini
oracle_enabled: false
