project: linux
project_url: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/
new_patch: be03df3d4bfe7e8866d4aa43d62e648ffe884f5f
new_patch_parent: 4b1a2c2a8e0ddcb89c5f6c5003bd9b53142f69e3
target_release: d2112b18b591eb219b61dbc86a04a58f6d6431c6
sanitizer: 
error_message: 
tag: 645a4616b87a2f10e398
project_dir: /path/to/local/linux-stable
patch_dataset_dir: /path/to/KBack-artifact/paired_patches/645a4616b87a2f10e398
api_key: <REDACTED>
api_url: <REDACTED>
model: gpt-4o-mini
oracle_enabled: false
