project: linux
project_url: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/
new_patch: fba383985354e83474f95f36d7c65feb75dba19d
new_patch_parent: 48dea8f7bb011608fd969749a1980f8311ef45f2
target_release: 2df8c16ea41d4eab9949f410e233f347aa657215
sanitizer: 
error_message: 
tag: 5186630949e3c55f0799
project_dir: /path/to/local/linux-stable
patch_dataset_dir: /path/to/KBack-artifact/paired_patches/5186630949e3c55f0799
api_key: <REDACTED>
api_url: <REDACTED>
model: gpt-4o-mini
oracle_enabled: false
