project: linux
project_url: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/
new_patch: 0ac4827f78c7ffe8eef074bc010e7e34bc22f533
new_patch_parent: 8092a0eed4080a33a4c8681f4231c40c0bb7cb5c
target_release: 918f42ca1d3fee0303f4dde8b7951e2fcd416ef7
sanitizer: 
error_message: 
tag: 03110230a11411024147
project_dir: /path/to/local/linux-stable
patch_dataset_dir: /path/to/KBack-artifact/paired_patches/03110230a11411024147
api_key: <REDACTED>
api_url: <REDACTED>
model: gpt-4o-mini
oracle_enabled: false
