project: linux
project_url: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/
new_patch: d679ae94fdd5d3ab00c35078f5af5f37e068b03d
new_patch_parent: f485922d8fe4e44f6d52a5bb95a603b7c65554bb
target_release: a34a5d160ca168c2be1efe421ba4e7a71f913209
sanitizer: 
error_message: 
tag: bdd6e38a1ed5ee58d8bd
project_dir: /path/to/local/linux-stable
patch_dataset_dir: /path/to/KBack-artifact/paired_patches/bdd6e38a1ed5ee58d8bd
api_key: <REDACTED>
api_url: <REDACTED>
model: gpt-4o-mini
oracle_enabled: false
