project: linux
project_url: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/
new_patch: a635415a064e77bcfbf43da413fd9dfe0bbed9cb
new_patch_parent: f443e374ae131c168a065ea1748feac6b2e76613
target_release: 48c624e7ecec3c11fc404160aba3989b0c38c3d4
sanitizer: 
error_message: 
tag: d55757faa9b80590767b
project_dir: /path/to/local/linux-stable
patch_dataset_dir: /path/to/KBack-artifact/paired_patches/d55757faa9b80590767b
api_key: <REDACTED>
api_url: <REDACTED>
model: gpt-4o-mini
oracle_enabled: false
