project: linux
project_url: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/
new_patch: 27b918007d96402aba10ed52a6af8015230f1793
new_patch_parent: 0142bbd21da64210287963722f7b25d26748ecf0
target_release: efd75512e38ac6699e0e8c020ba6b174738e352a
sanitizer: 
error_message: 
tag: b0c03d76056ef6cd12a6
project_dir: /path/to/local/linux-stable
patch_dataset_dir: /path/to/KBack-artifact/paired_patches/b0c03d76056ef6cd12a6
api_key: <REDACTED>
api_url: <REDACTED>
model: gpt-4o-mini
oracle_enabled: false
