project: linux
project_url: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/
new_patch: af8edaeddbc52e53207d859c912b017fd9a77629
new_patch_parent: 48327566769a6ff2e873b6bf075392bd756625ca
target_release: 5e1c91f4e6f7b92acb3c16368fd4a1017d9f472b
sanitizer: 
error_message: 
tag: 7f4643b267cc680bfa1c
project_dir: /path/to/local/linux-stable
patch_dataset_dir: /path/to/KBack-artifact/paired_patches/7f4643b267cc680bfa1c
api_key: <REDACTED>
api_url: <REDACTED>
model: gpt-4o-mini
oracle_enabled: false
