project: linux
project_url: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/
new_patch: 21a673bddc8fd4873c370caf9ae70ffc6d47e8d3
new_patch_parent: 33c563ebf8d3deed7d8addd20d77398ac737ef9a
target_release: e017b876600fe95abf9d1625992957ce801263e1
sanitizer: 
error_message: 
tag: b94a6818504ea90d7661
project_dir: /path/to/local/linux-stable
patch_dataset_dir: /path/to/KBack-artifact/paired_patches/b94a6818504ea90d7661
api_key: <REDACTED>
api_url: <REDACTED>
model: gpt-4o-mini
oracle_enabled: false
