project: linux
project_url: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/
new_patch: 131897c65e2b86cf14bec7379f44aa8fbb407526
new_patch_parent: c17b750b3ad9f45f2b6f7e6f7f4679844244f0b9
target_release: c5fff1c37e181c2a9c4f3709e7aba59127e5d74e
sanitizer: 
error_message: 
tag: 5a398eb460ddaa6f242f
project_dir: /path/to/local/linux-stable
patch_dataset_dir: /path/to/KBack-artifact/paired_patches/5a398eb460ddaa6f242f
api_key: <REDACTED>
api_url: <REDACTED>
model: gpt-4o-mini
oracle_enabled: false
