project: linux
project_url: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/
new_patch: cc16eecae687912238ee6efbff71ad31e2bc414e
new_patch_parent: e3952fcce1aad934f1322843b564ff86256444b2
target_release: b0412dd1c24b3405cc1a32a9298c6c876f31757d
sanitizer: 
error_message: 
tag: afa2ca5171d93e44b348
project_dir: /path/to/local/linux-stable
patch_dataset_dir: /path/to/KBack-artifact/paired_patches/afa2ca5171d93e44b348
api_key: <REDACTED>
api_url: <REDACTED>
model: gpt-4o-mini
oracle_enabled: false
