project: linux
project_url: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/
new_patch: 5bef3ac184b5626ea62385d6b82a1992b89d7940
new_patch_parent: 0469b410c888414c3505d8d2b5814eb372404638
target_release: 5bb4228c32261d06e4fbece37ec3828bcc005b6b
sanitizer: 
error_message: 
tag: 1fcd957a82e3a1baa94d
project_dir: /path/to/local/linux-stable
patch_dataset_dir: /path/to/KBack-artifact/paired_patches/1fcd957a82e3a1baa94d
api_key: <REDACTED>
api_url: <REDACTED>
model: gpt-4o-mini
oracle_enabled: false
