project: linux
project_url: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/
new_patch: d8a6213d70accb403b82924a1c229e733433a5ef
new_patch_parent: eaac25d026a14be4fe97683103f2a3ae76bff7bd
target_release: 2a523f14a3f53b46ff0e1fafd215b0bc5f6783aa
sanitizer: 
error_message: 
tag: 9ee20ec1de7b3168db09
project_dir: /path/to/local/linux-stable
patch_dataset_dir: /path/to/KBack-artifact/paired_patches/9ee20ec1de7b3168db09
api_key: <REDACTED>
api_url: <REDACTED>
model: gpt-4o-mini
oracle_enabled: false
