project: linux
project_url: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/
new_patch: 4e034bf045b12852a24d5d33f2451850818ba0c1
new_patch_parent: 7a425ec75d2bb30a1c959a8676ef8c5ef285095d
target_release: e7e5315212819143c88bb7b138079175af09f23f
sanitizer: 
error_message: 
tag: 80620e2d0d0a33b09f93
project_dir: /path/to/local/linux-stable
patch_dataset_dir: /path/to/KBack-artifact/paired_patches/80620e2d0d0a33b09f93
api_key: <REDACTED>
api_url: <REDACTED>
model: gpt-4o-mini
oracle_enabled: false
