project: linux
project_url: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/
new_patch: a298232ee6b9a1d5d732aa497ff8be0d45b5bd82
new_patch_parent: 50b7b6f29de3e18e9d6c09641256a0296361cfee
target_release: 5a5357cd2cd9a38944594eb5cd74377932e176bf
sanitizer: 
error_message: 
tag: a2910119328ce8e7996f
project_dir: /path/to/local/linux-stable
patch_dataset_dir: /path/to/KBack-artifact/paired_patches/a2910119328ce8e7996f
api_key: <REDACTED>
api_url: <REDACTED>
model: gpt-4o-mini
oracle_enabled: false
