project: linux
project_url: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/
new_patch: d864319871b05fadd153e0aede4811ca7008f5d6
new_patch_parent: 0271d28941cc8424f7979da692dea525f9fe1be9
target_release: 66c7aa157a38d93947b32c0d309889369a27e8e2
sanitizer: 
error_message: 
tag: b87c222546179f4513a7
project_dir: /path/to/local/linux-stable
patch_dataset_dir: /path/to/KBack-artifact/paired_patches/b87c222546179f4513a7
api_key: <REDACTED>
api_url: <REDACTED>
model: gpt-4o-mini
oracle_enabled: false
