project: linux
project_url: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/
new_patch: e53e9828a8d2c6545e01ff9711f1221f2fd199ce
new_patch_parent: 63214f02cff9ebd57be00e143de12107c66f5394
target_release: 76ef0d62e488e0df7435e715d1c130b42925bb1c
sanitizer: 
error_message: 
tag: 1638e7c770eef6b6c0d0
project_dir: /path/to/local/linux-stable
patch_dataset_dir: /path/to/KBack-artifact/paired_patches/1638e7c770eef6b6c0d0
api_key: <REDACTED>
api_url: <REDACTED>
model: gpt-4o-mini
oracle_enabled: false
