project: linux
project_url: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/
new_patch: 9f0933ac026f7e54fe096797af9de20724e79097
new_patch_parent: eb7081409f94a9a8608593d0fb63a1aa3d6f95d8
target_release: 1fb660ff7fcc053b6040872e100e2b2e14787202
sanitizer: 
error_message: 
tag: a76f6a6e524cf2080aa3
project_dir: /path/to/local/linux-stable
patch_dataset_dir: /path/to/KBack-artifact/paired_patches/a76f6a6e524cf2080aa3
api_key: <REDACTED>
api_url: <REDACTED>
model: gpt-4o-mini
oracle_enabled: false
