project: linux
project_url: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/
new_patch: 67f29896fdc83298eed5a6576ff8f9873f709228
new_patch_parent: 54d87913f147a983589923c7f651f97de9af5be1
target_release: 66ab7fcdac34b890017f04f391507ef5b2b89a13
sanitizer: 
error_message: 
tag: 36a7f280de4e11c6f04e
project_dir: /path/to/local/linux-stable
patch_dataset_dir: /path/to/KBack-artifact/paired_patches/36a7f280de4e11c6f04e
api_key: <REDACTED>
api_url: <REDACTED>
model: gpt-4o-mini
oracle_enabled: false
