project: linux
project_url: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/
new_patch: 18685451fc4e546fc0e718580d32df3c0e5c8272
new_patch_parent: 40d4b4807cadd83fb3f46cc8cd67a945b5b25461
target_release: 54720f68c4ad0ffb5a776e7a14b25f02242068cb
sanitizer: 
error_message: 
tag: e5167d7144a62715044c
project_dir: /path/to/local/linux-stable
patch_dataset_dir: /path/to/KBack-artifact/paired_patches/e5167d7144a62715044c
api_key: <REDACTED>
api_url: <REDACTED>
model: gpt-4o-mini
oracle_enabled: false
