project: linux
project_url: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/
new_patch: ea354b6ddd6f09be29424f41fa75a3e637fea234
new_patch_parent: 9d3b7ca42d6f70556c10ce3f6bdb32457077d947
target_release: b5c7ec6d15af79c910a0b5b9acbf60016d8c344d
sanitizer: 
error_message: 
tag: b4d54814b339b5c6bbd4
project_dir: /path/to/local/linux-stable
patch_dataset_dir: /path/to/KBack-artifact/paired_patches/b4d54814b339b5c6bbd4
api_key: <REDACTED>
api_url: <REDACTED>
model: gpt-4o-mini
oracle_enabled: false
