project: linux
project_url: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/
new_patch: 84b01721e8042cdd1e8ffeb648844a09cd4213e0
new_patch_parent: 136057256686de39cc3a07c2e39ef6bc43003ff6
target_release: d89e4211b51752daf063d638af50abed2fd5f96d
sanitizer: 
error_message: 
tag: aab53008a5adf26abe91
project_dir: /path/to/local/linux-stable
patch_dataset_dir: /path/to/KBack-artifact/paired_patches/aab53008a5adf26abe91
api_key: <REDACTED>
api_url: <REDACTED>
model: gpt-4o-mini
oracle_enabled: false
