project: linux
project_url: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/
new_patch: 6e455f5dcdd15fa28edf0ffb5b44d3508512dccf
new_patch_parent: 3823119b9c2b5f9e9b760336f75bc989b805cde6
target_release: 5c480a6966c5a2f8a96c8440b10a4acc0fc57624
sanitizer: 
error_message: 
tag: 4fad2e57beb6397ab2fc
project_dir: /path/to/local/linux-stable
patch_dataset_dir: /path/to/KBack-artifact/paired_patches/4fad2e57beb6397ab2fc
api_key: <REDACTED>
api_url: <REDACTED>
model: gpt-4o-mini
oracle_enabled: false
