project: linux
project_url: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/
new_patch: ee85e0938aa8f9846d21e4d302c3cf6a2a75110d
new_patch_parent: cc749e61c011c255d81b192a822db650c68b313f
target_release: 2a6579ef5f2576a940125729f7409cc182f1c8df
sanitizer: 
error_message: 
tag: 1ad8bac5af24d01e2cbd
project_dir: /path/to/local/linux-stable
patch_dataset_dir: /path/to/KBack-artifact/paired_patches/1ad8bac5af24d01e2cbd
api_key: <REDACTED>
api_url: <REDACTED>
model: gpt-4o-mini
oracle_enabled: false
