project: linux
project_url: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/
new_patch: 4b911a9690d72641879ea6d13cce1de31d346d79
new_patch_parent: a5b1051ad5a7028a4a5a2f569f8caf3a56c7163c
target_release: bcdac70adceb44373da204c3c297f2a98e13216e
sanitizer: 
error_message: 
tag: 42a0dc856239de4de60e
project_dir: /path/to/local/linux-stable
patch_dataset_dir: /path/to/KBack-artifact/paired_patches/42a0dc856239de4de60e
api_key: <REDACTED>
api_url: <REDACTED>
model: gpt-4o-mini
oracle_enabled: false
