project: linux
project_url: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/
new_patch: ddf2846f22e8575d6b4b6a66f2100f168b8cd73d
new_patch_parent: b61e69bb1c049cf507e3c654fa3dc1568231bd07
target_release: a2b560815528ae8e266fca6038bb5585d13aaef4
sanitizer: 
error_message: 
tag: 7c808908291a569281a9
project_dir: /path/to/local/linux-stable
patch_dataset_dir: /path/to/KBack-artifact/paired_patches/7c808908291a569281a9
api_key: <REDACTED>
api_url: <REDACTED>
model: gpt-4o-mini
oracle_enabled: false
