project: linux
project_url: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/
new_patch: bd1248f1ddbc48b0c30565fce897a3b6423313b8
new_patch_parent: a533b70a657c03137dd49cbcfee70aac086ab2b1
target_release: 5e87eabce7bc0286c7131c84335100983c31e3cf
sanitizer: 
error_message: 
tag: 97c5bd9cc81eca63d36e
project_dir: /path/to/local/linux-stable
patch_dataset_dir: /path/to/KBack-artifact/paired_patches/97c5bd9cc81eca63d36e
api_key: <REDACTED>
api_url: <REDACTED>
model: gpt-4o-mini
oracle_enabled: false
