project: linux
project_url: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/
new_patch: d0d1df8ba18abc57f28fb3bc053b2bf319367f2c
new_patch_parent: 2884dc7d08d98a89d8d65121524bb7533183a63a
target_release: 50569d12945f86fa4b321c4b1c3005874dbaa0f1
sanitizer: 
error_message: 
tag: 3ab78ff125b7979e45f9
project_dir: /path/to/local/linux-stable
patch_dataset_dir: /path/to/KBack-artifact/paired_patches/3ab78ff125b7979e45f9
api_key: <REDACTED>
api_url: <REDACTED>
model: gpt-4o-mini
oracle_enabled: false
