project: linux
project_url: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/
new_patch: 77618db346455129424fadbbaec596a09feaf3bb
new_patch_parent: ffc253263a1375a65fa6c9f62a893e9767fbebfa
target_release: f5fb5ac7cee29cea9156e734fd652a66417d32fc
sanitizer: 
error_message: 
tag: 1f2eb3e8cd123ffce499
project_dir: /path/to/local/linux-stable
patch_dataset_dir: /path/to/KBack-artifact/paired_patches/1f2eb3e8cd123ffce499
api_key: <REDACTED>
api_url: <REDACTED>
model: gpt-4o-mini
oracle_enabled: false
