project: linux
project_url: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/
new_patch: 79c1587b6cda74deb0c86fc7ba194b92958c793c
new_patch_parent: 6dfba108387bf4e71411b3da90b2d5cce48ba054
target_release: a76aba65e823f3c8866e3d8662e30e456f267ce3
sanitizer: 
error_message: 
tag: a725ab460fc1def9896f
project_dir: /path/to/local/linux-stable
patch_dataset_dir: /path/to/KBack-artifact/paired_patches/a725ab460fc1def9896f
api_key: <REDACTED>
api_url: <REDACTED>
model: gpt-4o-mini
oracle_enabled: false
