project: linux
project_url: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/
new_patch: 49bdb63ff64469a6de8ea901aef123c75be9bbe7
new_patch_parent: 07fdad3a93756b872da7b53647715c48d0f4a2d0
target_release: e298bf6f5579feda1044cc4f1ee842b135e9b422
sanitizer: 
error_message: 
tag: 62ec8226f01cb4ca19d9
project_dir: /path/to/local/linux-stable
patch_dataset_dir: /path/to/KBack-artifact/paired_patches/62ec8226f01cb4ca19d9
api_key: <REDACTED>
api_url: <REDACTED>
model: gpt-4o-mini
oracle_enabled: false
