project: linux
project_url: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/
new_patch: c0a2a1b0d631fc460d830f52d06211838874d655
new_patch_parent: ca8add922f9c7f6e2e3c71039da8e0dcc64b87ed
target_release: 230dc06e2495487d88b3410da055bb618febb19b
sanitizer: 
error_message: 
tag: 6177e1f90d92583bcc58
project_dir: /path/to/local/linux-stable
patch_dataset_dir: /path/to/KBack-artifact/paired_patches/6177e1f90d92583bcc58
api_key: <REDACTED>
api_url: <REDACTED>
model: gpt-4o-mini
oracle_enabled: false
