project: linux
project_url: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/
new_patch: c4e51e424e2c772ce1836912a8b0b87cd61bc9d5
new_patch_parent: 0bfe105018bd2d7b1e4373193d9b55b37cf4458b
target_release: 85bb85801910ff73db3d8cb7d0be2777b715fbae
sanitizer: 
error_message: 
tag: 7fb05ccf7b3d2f9617b3
project_dir: /path/to/local/linux-stable
patch_dataset_dir: /path/to/KBack-artifact/paired_patches/7fb05ccf7b3d2f9617b3
api_key: <REDACTED>
api_url: <REDACTED>
model: gpt-4o-mini
oracle_enabled: false
