project: linux
project_url: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/
new_patch: 05d9ea1ceb62a55af6727a69269a4fd310edf483
new_patch_parent: 22cad8bc1d36547cdae0eef316c47d917ce3147c
target_release: a50b796d36719757526ee094c703378895ab5e67
sanitizer: 
error_message: 
tag: 79d792676d8ac050949f
project_dir: /path/to/local/linux-stable
patch_dataset_dir: /path/to/KBack-artifact/paired_patches/79d792676d8ac050949f
api_key: <REDACTED>
api_url: <REDACTED>
model: gpt-4o-mini
oracle_enabled: false
