project: linux
project_url: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/
new_patch: e120b6388d7d88635d67dcae6483f39c37111850
new_patch_parent: 24de1b7b231cf01d08d12db26e66b0c46253a7da
target_release: 8650725bb0a48b206d5a8ddad3a7488f9a5985b7
sanitizer: 
error_message: 
tag: 1bc2c2afd44f820a669f
project_dir: /path/to/local/linux-stable
patch_dataset_dir: /path/to/KBack-artifact/paired_patches/1bc2c2afd44f820a669f
api_key: <REDACTED>
api_url: <REDACTED>
model: gpt-4o-mini
oracle_enabled: false
