project: linux
project_url: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/
new_patch: 7c4e39f9d2af4abaf82ca0e315d1fd340456620f
new_patch_parent: 3ed51857a50f530ac7a1482e069dfbd1298558d4
target_release: c71d114ef68c95da5a82ec85a721ab31f5bd905b
sanitizer: 
error_message: 
tag: 7325f164162e200000c1
project_dir: /path/to/local/linux-stable
patch_dataset_dir: /path/to/KBack-artifact/paired_patches/7325f164162e200000c1
api_key: <REDACTED>
api_url: <REDACTED>
model: gpt-4o-mini
oracle_enabled: false
