project: linux
project_url: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/
new_patch: 738d5a51864ed8d7a68600b8c0c63fe6fe5c4f20
new_patch_parent: 9282bc905f0949fab8cf86c0f620ca988761254c
target_release: a5bfb13b4f406aef1a450f99d22d3e48df01528c
sanitizer: 
error_message: 
tag: 356aed408415a56543cd
project_dir: /path/to/local/linux-stable
patch_dataset_dir: /path/to/KBack-artifact/paired_patches/356aed408415a56543cd
api_key: <REDACTED>
api_url: <REDACTED>
model: gpt-4o-mini
oracle_enabled: false
